repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.10
    hooks:
      # Run the formatter.
      - id: ruff-format src/
      # Run the linter.
      - id: ruff-check src/
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.400
    hooks:
      - id: pyright
        additional_dependencies: [matplotlib, pytest]