site_name: QwaveMPS Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Theory: theory.md
  - Modules: modules.md
  - Examples: examples.md
  - Contributing: contributing.md
  - References: references.md

theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      inline_wrap: "$"
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
