site_name: QwaveMPS Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Theory: theory.md
  - Modules: modules.md
  - Examples: examples.md
  - Contributing: contributing.md
  - References: references.md

theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - "https://polyfill.io/v3/polyfill.min.js?features=es6"
  - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
